language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-21.0.3
    - android-23
    - sys-img-armeabi-v7a-android-21

env:
  global:
    - TERM=dumb

before_script:
 - cd EscapeApp
 - chmod +x gradlew

script:
  - ./gradlew build connectedCheck
