language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.3
    - android-23
    - sys-img-armeabi-v7a-android-21
    - extra-android-m2repository

env:
  global:
    # Travis CI's terminal isn't smart, it's...
    - TERM=dumb
    # Directory where the app is located
    - TEST_DIR=EscapeApp
matrix:
    - ANDROID_TARGET=anroid-21 ANDROID_ABI=armeabi-v7a

before_script:
  # change directory to wherever the App is located
  - cd $TEST_DIR && echo $PWD
  # give gradlew script exec permissions
  - chmod a+x gradlew
  # we don't want to setup a custom virtual device
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  # run the emulator
  - emulator -avd test -no-skin -no-audio -no-window &
  # wait for the emulator to boot
  - android-wait-for-emulator
  # wake up the emulator (make sure the keyguard overlay disappears)
  - adb shell input keyevent 82 &
  - sleep 5
  
script:
  - adb shell input keyevent 82 &
  - sleep 2
  - ./gradlew test 
  - adb shell input keyevent 82 &
  - sleep 2
  - ./gradlew build connectedCheck

after_script:
  - ./gradlew pmd
  - echo "== PMD_RESULT =="; cat $TEST_DIR/app/build/reports/pmd/pmd.html echo "== END_PMD_RESULT =="
  - ./gradlew checkstyle
  - ./gradlew findbugs 
  - echo "== FINDBUGS_RESULT =="; $TEST_DIR/app/build/reports/findbugs/findbugs.html echo "== END_FINDBUGS_RESULT =="
