language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-21.0.3
    - android-21
    - sys-img-armeabi-v7a-android-21

before_script:
 - chmod +x EscapeApp/gradlew

script:
  - ./gradlew build connectedCheck
